#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaestroPad.Resource", IsApplication=true)]

namespace MaestroPad
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int ListeCouleur = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ListeNuance = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ListeReprise = 2130968578;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int Alertes = 2131034116;
			
			// aapt resource value: 0x7f050017
			public const int Binaire = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int ChargerPartition = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int ChoixAlerte = 2131034117;
			
			// aapt resource value: 0x7f050013
			public const int Home = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int ListeNuance = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ListeReprises = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int Mode = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int ModeMesure = 2131034133;
			
			// aapt resource value: 0x7f050025
			public const int Next = 2131034149;
			
			// aapt resource value: 0x7f050019
			public const int Notetempo = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int NouvellePartition = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Nuance = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int Reprise = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int Rien = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int Ternaire = 2131034136;
			
			// aapt resource value: 0x7f050022
			public const int Valtempo = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int back = 2131034148;
			
			// aapt resource value: 0x7f050012
			public const int createpartition = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int denominateur = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int gridLayout1 = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int namePartition = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int nbmesure = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int nbrmesures = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public const int notedutempo = 2131034138;
			
			// aapt resource value: 0x7f05000d
			public const int numerateur = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int partition = 2131034120;
			
			// aapt resource value: 0x7f05001b
			public const int radioButton1 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int radioButton2 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int radioButton3 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int radioButton4 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int radioButton5 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int radioButton6 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int radioButton8 = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int tempovaleur = 2131034147;
			
			// aapt resource value: 0x7f050010
			public const int valdenominateur = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int valnumerateur = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int zoomButton1 = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int NuancesAlerte = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Parametrage = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Parametragesecondaire = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
